// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package cw305_usb_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 2;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {logic [31:0] q;} cw305_usb_reg2hw_echo_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } cw305_usb_hw2reg_echo_reg_t;

  // Register -> HW type
  typedef struct packed {
    cw305_usb_reg2hw_echo_reg_t echo;  // [31:0]
  } cw305_usb_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    cw305_usb_hw2reg_echo_reg_t echo;  // [32:0]
  } cw305_usb_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] CW305_USB_ECHO_OFFSET = 2'h0;

  // Register index
  typedef enum int {CW305_USB_ECHO} cw305_usb_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] CW305_USB_PERMIT[1] = '{
      4'b1111  // index[0] CW305_USB_ECHO
  };

endpackage

