# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ando/git/x-heep-tflite/build/openhwgroup.org_systems_core-v-mini-mcu_1.0.4/cw305-vivado/openhwgroup.org_systems_core-v-mini-mcu_1.0.4.srcs/sources_1/ip/xilinx_mem_gen_8192/xilinx_mem_gen_8192.xci
# IP: The module: 'xilinx_mem_gen_8192' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ando/git/x-heep-tflite/build/openhwgroup.org_systems_core-v-mini-mcu_1.0.4/cw305-vivado/openhwgroup.org_systems_core-v-mini-mcu_1.0.4.gen/sources_1/ip/xilinx_mem_gen_8192/xilinx_mem_gen_8192_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_mem_gen_8192'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/ando/git/x-heep-tflite/build/openhwgroup.org_systems_core-v-mini-mcu_1.0.4/cw305-vivado/openhwgroup.org_systems_core-v-mini-mcu_1.0.4.srcs/sources_1/ip/xilinx_mem_gen_8192/xilinx_mem_gen_8192.xci
# IP: The module: 'xilinx_mem_gen_8192' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ando/git/x-heep-tflite/build/openhwgroup.org_systems_core-v-mini-mcu_1.0.4/cw305-vivado/openhwgroup.org_systems_core-v-mini-mcu_1.0.4.gen/sources_1/ip/xilinx_mem_gen_8192/xilinx_mem_gen_8192_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_mem_gen_8192'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
